services:
  provide:
    build: .
    #command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - .env:/app/.env
      # Bind mount to include seeded files and persist locally
      - ./media:/app/media
      - ./uploads:/app/uploads
    ports:
      - "8001:8000"

# Named volumes for persistence
volumes: {}
